### ISSUE TITLE
minimal case issue

### ISSUE THREAD

**Issue by coolgw** [coolgw/Matrix#29]
SCC-ADDONS 没有minimal这个设置 https://openqa.nue.suse.com/tests/4552884#step/register_system/61

SCC_ADDONS=base
replace FULL_UPDATE =1 to MINIMAL_UPDATE=1

**Comment by coolgw** [comment]
test case name also need update
online_SLES_15_SP2_pscc_minimal_all_full_zypp   --> minimal 和full是一个位置

online_SLES_15_SP2_pscc_all_minimal_zypp

**Comment by hjluo** [comment]
can we use ADDON_REGBYCMD for HPC to speed up the migration time

**Comment by coolgw** [comment]
> ADDON_REGBYCMD
t
any strategy for ADDON_REGBYCMD?  But i am afraid if we all it for all case 
1) not real save time, since 15sp2 is fresh still, do not expect much patch
2) we will skip UI level test? 
anyway, we can discuss this
