### ISSUE TITLE
spvm case don't need qcow file and mimial case has wrong setting

### ISSUE THREAD

**Issue by tinawang123** [coolgw/Matrix#31]
For minimal case:
offline_SLES_15_SP2_pscc_minimal_all_full
should not SCC_ADDONS: 'minimal' but MINIMAL_UPDATE=1
For offline setting don't need set HDD_1 but：
ISO=SLE-%VERSION%-Full-%ARCH%-Build%BUILD%-Media1.iso
MIRROR_HTTP=http://openqa.suse.de/assets/repo/SLE-%VERSION%-Full-%ARCH%-Build%BUILD%-Media1
REPO_0=SLE-%VERSION%-Full-%ARCH%-Build%BUILD%-Media1
For online
Change Full to Oline

**Comment by coolgw** [comment]
@tinawang123   why you need ISO and REPO_0 same time, i suppose using REPO_0 is enough for pvm case?

**Comment by coolgw** [comment]
Current logic is only set REPO_0, not set ISO since i thought pvm only need REPO_0 same as s390.
Also we only set fulldvd in case (offline and media)
feedback me if not correct.

**Comment by hjluo** [comment]
[Setting]No livepatch on aarch64, need to remove in scc_addon

**Comment by tinawang123** [comment]
offline pscc use Online 
offline media use Full
spvm need
MIRROR_HTTP=http://openqa.suse.de/assets/repo/SLE-%VERSION%-Full-%ARCH%-Build%BUILD%-Media1
REPO_0=SLE-%VERSION%-Full-%ARCH%-Build%BUILD%-Media1
ISO don't need. It will write to PXE server to start bootloader. This is different with s390x

**Comment by coolgw** [comment]
> [Setting]No livepatch on aarch64, need to remove in scc_addon

please add new issue , not add comments  for live patch you can check latest version, it already fixed.
