### ISSUE TITLE
iso_maxsize=0 for full media

### ISSUE THREAD

**Issue by hjluo** [coolgw/Matrix#36]
这个应该是设定 ISO_MAXSIZE=0
Full media iso 大， 不是hdd 的问题

tinawang123

Full 设置为0

**Comment by hjluo** [comment]
FULL or ONLINE media size不同 flavor里设的应该是online的 所以需要给media的设置iso_maxsize=0 以避免检查 
        - Lemon

**Comment by coolgw** [comment]
for script, if iso is full cd, then  ISO_MAXSIZE=0
