### ISSUE TITLE
offline_SLE_HPC_15_SP2_pscc_basesys-desk-dev-hpc-python2-srv-wsm_def_full_tm

### ISSUE THREAD

**Issue by hjluo** [coolgw/Matrix#38]
offline_SLE_HPC_15_SP2_pscc_basesys-desk-dev-hpc-python2-srv-wsm_def_full_tm
in hpc_offline defined 2 times

**Comment by hjluo** [comment]
###start hpc aarch64 p1
    - offline_SLE_HPC_15_SP2_pscc_basesys-desk-dev-hpc-python2-srv-wsm_def_full_tm:
        testsuite: null
        settings:
          UPGRADE: '1'
          DESKTOP: 'textmode'
          PATCH: '1'
          ROLLBACK_AFTER_MIGRATION: '1'
          FULL_UPDATE: '1'
          HDDVERSION: '15-SP2'
          HDD_1: 'SLEHPC-15-SP2-%ARCH%-GM-TEXTMODE.qcow2'
          +ISO: 'SLE-%VERSION%-Full-%ARCH%-Build%BUILD%-Media1.iso'
          ISO_MAXSIZE: '0'
          SLE_PRODUCT: 'hpc'
          KEEP_REGISTERED: '1'
          SCC_ADDONS: 'base,desk,dev,hpc,python2,srv,wsm'
          BOOTFROM: 'd'

    - offline_SLE_HPC_15_SP2_pscc_basesys-desk-dev-hpc-python2-srv-wsm_def_full_tm:
        testsuite: null
        settings:
          UPGRADE: '1'
          DESKTOP: 'textmode'
          PATCH: '1'
          ROLLBACK_AFTER_MIGRATION: '1'
          FULL_UPDATE: '1'
          HDDVERSION: '15-SP2'
          HDD_1: 'SLEHPC-15-SP2-%ARCH%-GM-TEXTMODE.qcow2'
          SLE_PRODUCT: 'hpc'
          KEEP_REGISTERED: '1'
          SCC_ADDONS: 'base,desk,dev,hpc,python2,srv,wsm'
          BOOTFROM: 'd'

**Comment by coolgw** [comment]
The reason is caused by design of Matrix,  the second case module is recommended+contm+lp but contm/lp not support on aarch.
so i removed this case.
