### ISSUE TITLE
online_SLE_HPC_15_SP2_pscc_basesys-desk-dev-hpc-python2-srv-wsm_def_full_zypp_ms

### ISSUE THREAD

**Issue by hjluo** [coolgw/Matrix#43]
on aarch64 hpc online p1

online_SLE_HPC_15_SP2_pscc_basesys-desk-dev-hpc-python2-srv-wsm_def_full_zypp_ms defined 2 times.

"
    - online_SLE_HPC_15_SP2_pscc_basesys-desk-dev-hpc-python2-srv-wsm_def_full_zypp_ms:
        testsuite: null
        settings:
          UPGRADE: '1'
          DESKTOP: 'textmode'
          PATCH: '1'
          ROLLBACK_AFTER_MIGRATION: '1'
          FULL_UPDATE: '1'
          HDDVERSION: '15-SP2'
          HDD_1: 'SLEHPC-15-SP2-%ARCH%-GM-SERVER.qcow2'
          SLE_PRODUCT: 'hpc'
          SCC_ADDONS: 'base,desktop,dev,hpc,python2,serverapp,wsm'
          ONLINE_MIGRATION: '1'
          BOOT_HDD_IMAGE: '1'
          MIGRATION_METHOD: 'zypper'
          BOOTFROM: 'd'

    - online_SLE_HPC_15_SP2_pscc_basesys-desk-dev-hpc-python2-srv-wsm_def_full_zypp_ms:
        testsuite: null
        settings:
          UPGRADE: '1'
          DESKTOP: 'textmode'
          PATCH: '1'
          ROLLBACK_AFTER_MIGRATION: '1'
          FULL_UPDATE: '1'
          HDDVERSION: '15-SP2'
          HDD_1: 'SLEHPC-15-SP2-%ARCH%-GM-SERVER.qcow2'
          SLE_PRODUCT: 'hpc'
          SCC_ADDONS: 'base,desktop,dev,hpc,python2,serverapp,wsm'
          ONLINE_MIGRATION: '1'
          BOOT_HDD_IMAGE: '1'
          MIGRATION_METHOD: 'zypper'
          BOOTFROM: 'd'

"

**Comment by coolgw** [comment]
remove duplicate one
